EXP_NAME: ppoewc
TRACK: True
CAPTURE_VIDEO: True

EVAL_DURING_TRAIN: True
EVAL_EVERY: 200

PIXEL_BASED: False
NATIVE_DOWNSCALING: True
PIXEL_RESIZE_SHAPE: [84, 84]
SMOOTH_IMAGE: False

FRAME_STACK: 4

SAVE_MODEL: True
UPLOAD_MODEL: False
HF_ENTITY: ""

TASKS: [pong, pong, pong] # replaces ENV_ID
TIMESTEPS_PER_TASK: 2000000  # replaces TOTAL_TIMESTEPS

TRAIN_MODS: # mods applied during training, for each environment
  - []
  - [shift_enemy]
  - [lazy_enemy]
EVAL_MODS:  # mods applied during evaluation, for each environment
  - []
  - [shift_enemy]
  - [lazy_enemy]

LEARNING_RATE: 0.00025
NUM_ENVS: 8
NUM_STEPS: 128
ANNEAL_LR: True
GAMMA: 0.99
GAE_LAMBDA: 0.95
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 4
NORM_ADV: True
CLIP_COEF: 0.1
CLIP_VLOSS: False
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
TARGET_KL: null
